name: ImgFeatAlign

# ----------------------------
# Transformer / Attention params
# ----------------------------
max_followup: 5
feature_dim: 512
finetune_all: false

num_heads: 8
dropout: 0.1
ffn_expansion_factor: 4

# ----------------------------
# Positional Encoding
# ----------------------------
pos_encoding_dim: 512