name: ImgFeatAlign

# ----------------------------
# Transformer / Attention params
# ----------------------------
max_followup: 5
num_attn_blocks: 1
feature_dim: 1536
finetune_all: false

heads: 4
dropout: 0.3
drop_path: 0.2
ffn_expansion_factor: 2

# ----------------------------
# Positional Encoding
# ----------------------------
pos_encoding_dim: 512