site_name: BCRBench

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started: getting-started.md
  - Datasets:
    - Overview: datasets/index.md
    - Preprocessing: datasets/preprocessing.md
    - CSV-File Creation: datasets/csv_file_creation.md
  - Models:
      - Overview: models/index.md
      - OA-BreaCR: models/oabreacr.md
      - ImgFeatAlign: models/imgfeatalign.md
      - LMV-Net: models/lmvnet.md
      - Mirai: models/mirai.md
      - VMRA-MaR: models/vmramar.md
      - Adding new models: models/adding_new_models.md
  - Training:
      - Overview: training/index.md
      - Training a Model: training/training_a_model.md
  - Evaluation:
      - Overview: evaluation/index.md
      - Evaluating a Model: evaluation/evaluating_a_model.md
